export enum userTypes {
  UPDATE_USER_CONNECTE = "UPDATE_USER_CONNECTE",
  SET_LOADING = "SET_LOADING",
  CLEAR_LOADING = "CLEAR_LOADING",
  UPDATE_USER_SIDEBAR_PERMISSION = "UPDATE_USER_SIDEBAR_PERMISSION",
}

export default userTypes;
